### ISSUE TITLE
Azure deployment from source - defining the project to deploy

### ISSUE THREAD

**Issue by RyanONeill1970** [onetrueerror/OneTrueError.Server#27]
I've forked the project and I'm setting it up for auto deploy in Azure, but it (Azure) gets confused as to which project it should build and deploy.

I know how to fix this (from https://github.com/projectkudu/kudu/wiki/Customizing-deployments).

My question is, would you like me to create a .deployment file as per the link above and offer it as a pull request? I appreciate you might not want this choice defined in the repo.

If you don't want it, I'll just have the project specified via the app config settings.

**Comment by gauffininteractive** [comment]
That would be a great contribution. Thank you for suggesting it.
