### ISSUE TITLE
Role SysAdmin is based on accountId instead of IsSysAdmin flag

### ISSUE THREAD

**Issue by carlbjorknas** [onetrueerror/OneTrueError.Server#31]
The first account that was added for me got the id 3. And it seems that although I set the IsSysAdmin flag to true, the menu isn't shown to me, probably because the role seem to be based on the id instead of the flag?

`var roles = accountId == 1 ? new[] {OneTrueClaims.RoleSysAdmin} : new string[0];`

**Comment by onetrueerror** [comment]
corrected in next commit
